[phases.setup]
nixPkgs = ['python311', 'nodejs_18']

[phases.install]
cmds = ['pip install -r requirements.txt']

[phases.build]
cmds = ['cd frontend && npm ci && npm run build']

[start]
cmd = 'uvicorn main:app --host 0.0.0.0 --port $PORT --workers 4'
